#title in header
title: "Newtime's Blog"

#main info
#owner
owner: "Newtime"
email: newtime@anche.no
info: "è®°å½•ç”Ÿæ´»ï¼Œåˆ†äº«æ€è€ƒï¼Œåœ¨æ•°å­—ä¸–ç•Œç•™ä¸‹ç—•è¿¹"
#description
desc: ""

#menu
menu:
  å·¥ä½œ: /work
  ç”Ÿæ´»: /life
  å­¦ä¹ : /study
  å…¶ä»–: /other

#index/main page max show posts (in number)
max_post: 8

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/adisaktijrs
linkedin: https://linkedin.com/in/adisaktijrs
twitter: https://twitter.com/adisaktijrs
instagram: https://instagram.com/adisaktijrs
stackoverflow: https://stackoverflow.com/story/tobiasreithmeier

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
